### PR TITLE
Add sweepai/sweep

### PR DESCRIPTION
**Pull request by wwzeng1**

### CODE REVIEW

**Comment by wwzeng1** [comment]
https://github.com/sweepai/sweep/pulls?q=is%3Apr+label%3Asweep+is%3Amerged

evidence it works 😄

**Comment by wwzeng1** [comment]
Could we move this to Agent?

**Comment by wwzeng1** [comment]
We do a lot more than write the PR, we also perform testing, linting, and run github actions.

**Comment by kevinlu1248** [comment]
@jamesmurdza Made another PR here with more details on this https://github.com/jamesmurdza/awesome-ai-devtools/pull/17

**Pull request closed without merging**
